# Generated by Django 2.0.7 on 2018-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing_items',
            name='product_price',
            field=models.IntegerField(max_length=7),
        ),
    ]
