# Generated by Django 2.0.7 on 2018-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenses_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_details',
            name='parchased_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='purchasing_items',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
