# Generated by Django 2.0.7 on 2018-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20180717_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_details',
            name='parchased_price',
            field=models.IntegerField(),
        ),
    ]
